name: Coffee Isometric Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Isometric Graph
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # ADIM 1: Ayar dosyasını oluştur (Gruvbox Teması)
      - name: Create Config File
        run: |
          echo '{
              "backgroundColor": "#282828",
              "foregroundColor": "#504945",
              "strongColor": "#fb4934",
              "mediumColor": "#fe8019",
              "weakColor": "#fabd2f",
              "radarColor": "#fabd2f",
              "growingAnimation": true
          }' > gruvbox_config.json

      # ADIM 2: Grafiği oluştur (Dosya yolunu göstererek)
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: gruvbox_config.json

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated coffee graph"
          git push origin HEAD:output --force
