name: Coffee Isometric Graph

on:
  schedule:
    - cron: "0 0 * * *" # Her gece yarısı çalış
  workflow_dispatch:
  push:
    branches:
    - master
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Isometric Graph
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          USERNAME: ${{ github.repository_owner }}
          # ÖZEL GRUVBOX KAHVE RENK AYARLARI
          SETTING_JSON: |
            {
                "backgroundColor": "#282828",
                "foregroundColor": "#504945",
                "strongColor": "#fb4934",
                "mediumColor": "#fe8019",
                "weakColor": "#fabd2f",
                "radarColor": "#fabd2f",
                "growingAnimation": true
            }
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated coffee graph"
          git push origin main:output --force
